//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Carsharing
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Car.
    /// </summary>
    // *** Start programmer edit section *** (Car CustomAttributes)

    // *** End programmer edit section *** (Car CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CarE", new string[] {
            "CarModel as \'Car model\'",
            "CarNumber as \'Car number\'",
            "CarOdometer as \'Car odometer\'"})]
    [View("CarL", new string[] {
            "CarModel as \'Car model\'",
            "CarNumber as \'Car number\'",
            "CarOdometer as \'Car odometer\'"})]
    public class Car : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Carsharing.tModel fCarModel;
        
        private string fCarNumber;
        
        private int fCarOdometer;
        
        // *** Start programmer edit section *** (Car CustomMembers)

        // *** End programmer edit section *** (Car CustomMembers)

        
        /// <summary>
        /// CarModel.
        /// </summary>
        // *** Start programmer edit section *** (Car.CarModel CustomAttributes)

        // *** End programmer edit section *** (Car.CarModel CustomAttributes)
        public virtual IIS.Carsharing.tModel CarModel
        {
            get
            {
                // *** Start programmer edit section *** (Car.CarModel Get start)

                // *** End programmer edit section *** (Car.CarModel Get start)
                IIS.Carsharing.tModel result = this.fCarModel;
                // *** Start programmer edit section *** (Car.CarModel Get end)

                // *** End programmer edit section *** (Car.CarModel Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Car.CarModel Set start)

                // *** End programmer edit section *** (Car.CarModel Set start)
                this.fCarModel = value;
                // *** Start programmer edit section *** (Car.CarModel Set end)

                // *** End programmer edit section *** (Car.CarModel Set end)
            }
        }
        
        /// <summary>
        /// CarNumber.
        /// </summary>
        // *** Start programmer edit section *** (Car.CarNumber CustomAttributes)

        // *** End programmer edit section *** (Car.CarNumber CustomAttributes)
        [StrLen(255)]
        public virtual string CarNumber
        {
            get
            {
                // *** Start programmer edit section *** (Car.CarNumber Get start)

                // *** End programmer edit section *** (Car.CarNumber Get start)
                string result = this.fCarNumber;
                // *** Start programmer edit section *** (Car.CarNumber Get end)

                // *** End programmer edit section *** (Car.CarNumber Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Car.CarNumber Set start)

                // *** End programmer edit section *** (Car.CarNumber Set start)
                this.fCarNumber = value;
                // *** Start programmer edit section *** (Car.CarNumber Set end)

                // *** End programmer edit section *** (Car.CarNumber Set end)
            }
        }
        
        /// <summary>
        /// CarOdometer.
        /// </summary>
        // *** Start programmer edit section *** (Car.CarOdometer CustomAttributes)

        // *** End programmer edit section *** (Car.CarOdometer CustomAttributes)
        public virtual int CarOdometer
        {
            get
            {
                // *** Start programmer edit section *** (Car.CarOdometer Get start)

                // *** End programmer edit section *** (Car.CarOdometer Get start)
                int result = this.fCarOdometer;
                // *** Start programmer edit section *** (Car.CarOdometer Get end)

                // *** End programmer edit section *** (Car.CarOdometer Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Car.CarOdometer Set start)

                // *** End programmer edit section *** (Car.CarOdometer Set start)
                this.fCarOdometer = value;
                // *** Start programmer edit section *** (Car.CarOdometer Set end)

                // *** End programmer edit section *** (Car.CarOdometer Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CarE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CarE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CarE", typeof(IIS.Carsharing.Car));
                }
            }
            
            /// <summary>
            /// "CarL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CarL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CarL", typeof(IIS.Carsharing.Car));
                }
            }
        }
    }
}
