//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Carsharing
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// City.
    /// </summary>
    // *** Start programmer edit section *** (City CustomAttributes)

    // *** End programmer edit section *** (City CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("CityE", new string[] {
            "Name as \'Name\'",
            "Car as \'Car\'",
            "Car.CarNumber as \'Car number\'"}, Hidden=new string[] {
            "Car.CarNumber"})]
    [MasterViewDefineAttribute("CityE", "Car", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "CarNumber")]
    [View("CityL", new string[] {
            "Name as \'Name\'",
            "Car.CarNumber as \'Car number\'"})]
    public class City : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.Carsharing.Car fCar;
        
        // *** Start programmer edit section *** (City CustomMembers)

        // *** End programmer edit section *** (City CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (City.Name CustomAttributes)

        // *** End programmer edit section *** (City.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (City.Name Get start)

                // *** End programmer edit section *** (City.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (City.Name Get end)

                // *** End programmer edit section *** (City.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (City.Name Set start)

                // *** End programmer edit section *** (City.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (City.Name Set end)

                // *** End programmer edit section *** (City.Name Set end)
            }
        }
        
        /// <summary>
        /// City.
        /// </summary>
        // *** Start programmer edit section *** (City.Car CustomAttributes)

        // *** End programmer edit section *** (City.Car CustomAttributes)
        [NotNull()]
        public virtual IIS.Carsharing.Car Car
        {
            get
            {
                // *** Start programmer edit section *** (City.Car Get start)

                // *** End programmer edit section *** (City.Car Get start)
                IIS.Carsharing.Car result = this.fCar;
                // *** Start programmer edit section *** (City.Car Get end)

                // *** End programmer edit section *** (City.Car Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (City.Car Set start)

                // *** End programmer edit section *** (City.Car Set start)
                this.fCar = value;
                // *** Start programmer edit section *** (City.Car Set end)

                // *** End programmer edit section *** (City.Car Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "CityE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CityE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CityE", typeof(IIS.Carsharing.City));
                }
            }
            
            /// <summary>
            /// "CityL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View CityL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("CityL", typeof(IIS.Carsharing.City));
                }
            }
        }
    }
}
