//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Carsharing
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Park.
    /// </summary>
    // *** Start programmer edit section *** (Park CustomAttributes)

    // *** End programmer edit section *** (Park CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ParkE", new string[] {
            "Address as \'Address\'",
            "City as \'City\'",
            "City.Name as \'Name\'"}, Hidden=new string[] {
            "City.Name"})]
    [MasterViewDefineAttribute("ParkE", "City", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("ParkL", new string[] {
            "Address as \'Address\'",
            "City.Name as \'Name\'"})]
    public class Park : ICSSoft.STORMNET.DataObject
    {
        
        private string fAddress;
        
        private IIS.Carsharing.City fCity;
        
        // *** Start programmer edit section *** (Park CustomMembers)

        // *** End programmer edit section *** (Park CustomMembers)

        
        /// <summary>
        /// Address.
        /// </summary>
        // *** Start programmer edit section *** (Park.Address CustomAttributes)

        // *** End programmer edit section *** (Park.Address CustomAttributes)
        [StrLen(255)]
        public virtual string Address
        {
            get
            {
                // *** Start programmer edit section *** (Park.Address Get start)

                // *** End programmer edit section *** (Park.Address Get start)
                string result = this.fAddress;
                // *** Start programmer edit section *** (Park.Address Get end)

                // *** End programmer edit section *** (Park.Address Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Park.Address Set start)

                // *** End programmer edit section *** (Park.Address Set start)
                this.fAddress = value;
                // *** Start programmer edit section *** (Park.Address Set end)

                // *** End programmer edit section *** (Park.Address Set end)
            }
        }
        
        /// <summary>
        /// Park.
        /// </summary>
        // *** Start programmer edit section *** (Park.City CustomAttributes)

        // *** End programmer edit section *** (Park.City CustomAttributes)
        [NotNull()]
        public virtual IIS.Carsharing.City City
        {
            get
            {
                // *** Start programmer edit section *** (Park.City Get start)

                // *** End programmer edit section *** (Park.City Get start)
                IIS.Carsharing.City result = this.fCity;
                // *** Start programmer edit section *** (Park.City Get end)

                // *** End programmer edit section *** (Park.City Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Park.City Set start)

                // *** End programmer edit section *** (Park.City Set start)
                this.fCity = value;
                // *** Start programmer edit section *** (Park.City Set end)

                // *** End programmer edit section *** (Park.City Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ParkE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ParkE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ParkE", typeof(IIS.Carsharing.Park));
                }
            }
            
            /// <summary>
            /// "ParkL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ParkL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ParkL", typeof(IIS.Carsharing.Park));
                }
            }
        }
    }
}
