//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Carsharing
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Model.
    /// </summary>
    // *** Start programmer edit section *** (tModel CustomAttributes)

    // *** End programmer edit section *** (tModel CustomAttributes)
    public enum tModel
    {
        
        // *** Start programmer edit section *** (tModel.Hyundai CustomAttributes)

        // *** End programmer edit section *** (tModel.Hyundai CustomAttributes)
        [Caption("Hyundai")]
        Hyundai,
        
        // *** Start programmer edit section *** (tModel.VM CustomAttributes)

        // *** End programmer edit section *** (tModel.VM CustomAttributes)
        [Caption("VM Polo")]
        VM,
        
        // *** Start programmer edit section *** (tModel.Renaut CustomAttributes)

        // *** End programmer edit section *** (tModel.Renaut CustomAttributes)
        [Caption("Renaut")]
        Renaut,
        
        // *** Start programmer edit section *** (tModel.Benz CustomAttributes)

        // *** End programmer edit section *** (tModel.Benz CustomAttributes)
        [Caption("Benz")]
        Benz,
    }
}
