//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Carsharing
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Plan.
    /// </summary>
    // *** Start programmer edit section *** (tPlan CustomAttributes)

    // *** End programmer edit section *** (tPlan CustomAttributes)
    public enum tPlan
    {
        
        // *** Start programmer edit section *** (tPlan.Per CustomAttributes)

        // *** End programmer edit section *** (tPlan.Per CustomAttributes)
        [Caption("Per Minute")]
        Per,
        
        // *** Start programmer edit section *** (tPlan.Rent CustomAttributes)

        // *** End programmer edit section *** (tPlan.Rent CustomAttributes)
        [Caption("Rent for Day")]
        Rent,
    }
}
